name: ci

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  dataset: ci_test
  validation_single_run: '011329'
  validation_run_group: B # FIXME: not actually used; see comments mentioning this variable below

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  dep_a:
    runs-on: ubuntu-latest
    steps:
    - name: do
      run: exit 0

  dep_b:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        code: [0, 1]
    steps:
    - name: do
      run: exit ${{ matrix.code }}
   
  deploy_timelines:
    name: Deployment
    needs:
      - dep_a
      - dep_b
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: check
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
        run: |
          echo "### Some tests failed." >> $GITHUB_STEP_SUMMARY
          exit 1
      - name: pass
        run: echo "### All tests passed." >> $GITHUB_STEP_SUMMARY
